//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicators_Property
    {
        public int Id { get; set; }
        public Nullable<int> IndicatorId { get; set; }
        public Nullable<int> PropertyId { get; set; }
    
        public virtual Indicator Indicator { get; set; }
        public virtual Property Property { get; set; }
    }
}
