//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.Activity_Property = new HashSet<Activity_Property>();
            this.Images = new HashSet<Image>();
            this.Indicators_Property = new HashSet<Indicators_Property>();
        }
    
        public int Id { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> AdvertTypeId { get; set; }
        public Nullable<int> PropertyTypeId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> SettlementId { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public Nullable<int> RepairTypeId { get; set; }
        public Nullable<int> SellTypeId { get; set; }
        public Nullable<int> MetroId { get; set; }
        public Nullable<int> OwnerTypeId { get; set; }
        public Nullable<int> FloorCountId { get; set; }
        public Nullable<int> ConstProjectId { get; set; }
        public Nullable<int> RoomCountId { get; set; }
        public string Adress { get; set; }
        public Nullable<int> Price { get; set; }
        public string About { get; set; }
        public string OwnerName { get; set; }
        public string OwnerNumber { get; set; }
        public string OwnerEmail { get; set; }
        public string OwnerAbout { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<decimal> LandArea { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity_Property> Activity_Property { get; set; }
        public virtual Advert_Type Advert_Type { get; set; }
        public virtual City City { get; set; }
        public virtual Constructor_Project Constructor_Project { get; set; }
        public virtual Country Country { get; set; }
        public virtual Document_Type Document_Type { get; set; }
        public virtual Floor_Count Floor_Count { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indicators_Property> Indicators_Property { get; set; }
        public virtual Metro Metro { get; set; }
        public virtual Owner_Type Owner_Type { get; set; }
        public virtual Propert_Type Propert_Type { get; set; }
        public virtual Region Region { get; set; }
        public virtual Repair_Type Repair_Type { get; set; }
        public virtual Room_Count Room_Count { get; set; }
        public virtual Sell_Type Sell_Type { get; set; }
        public virtual Settlement Settlement { get; set; }
        public virtual Status Status { get; set; }
    }
}
